config/routes.rb
Rails.application.routes.draw do

 resources :stations
  root to: 'home#index'

 resources :lines

 resources :stops

 resources :buses

 resources :arrivals
end

app/models/arrival.rb
class Arrival < ActiveRecord::Base
  validates :time, presence: true
  belongs_to :stop
  belongs_to :bus

  def names
    "#{stop.station.name}" + " - " + "#{stop.line.name}"
  end
end

app/models/bus.rb
class Bus < ActiveRecord::Base
  validates :number, presence: true
  belongs_to :line
  has_many :arrivals
end

app/models/line.rb
class Line < ActiveRecord::Base
  validates :name, presence: true
  has_many :stops
  has_many :buses
  has_many :stations, :through => :stops, dependent: :destroy
end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :name, presence: true
  has_many :stops
  has_many :lines, :through => :stops, dependent: :destroy
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  validates :line_id, presence: true
  validates :station_id, presence: true
  belongs_to :line
  belongs_to :station
  has_many :arrivals

  def station_name
    "#{station.name}" + " | " + "#{line.name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/arrivals_controller.rb
class ArrivalsController < ApplicationController
  def index
    @arrivals = Arrival.all
  end

  def new
    @arrival = Arrival.new
  end

  def create
    @arrival = Arrival.create(user_params)
    if @arrival.valid?
      flash[:notice] = "New Arrival Added"
      redirect_to arrival_path(@arrival)
    else
      render 'new'
    end
  end

  def show
    @arrival = Arrival.find(params[:id])
  end

  def edit
    @arrival = Arrival.find(params[:id])
  end

  def update
    @arrival = Arrival.find(params[:id])
    if @arrival.update(user_params)
      flash[:notice] = "Arrival updated"
      redirect_to arrival_path(@arrival)
    else
      render 'edit'
    end
  end

  def destroy
    @arrival = Arrival.find(params[:id])
    @arrival.destroy
    flash[:notice] = "This bus will no longer arrive at #{@arrival.names} at #{@arrival.time}"
    redirect_to arrivals_path
  end


  private
  def user_params
    params.require(:arrival).permit(:time, :stop_id, :bus_id)
  end
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
 def index
    @buses = Bus.all
  end

  def new
    @bus= Bus.new
  end

  def create
    @bus = Bus.create(user_params)
    if @bus.valid?
      flash[:notice] = "New Bus Added"
      redirect_to bus_path(@bus)
    else
      render 'new'
    end
  end

  def show
    @bus = Bus.find(params[:id])
  end

  def edit
    @bus = Bus.find(params[:id])
  end

  def update
    @bus = Bus.find(params[:id])
    if @bus.update(user_params)
      flash[:notice] = "This bus has been updated"
      redirect_to bus_path(@bus)
    else
      render 'edit'
    end
  end

  def destroy
    @bus = Bus.find(params[:id])
    @bus.destroy
    flash[:notice]= "Bus number #{@bus.number} has been deleted."
    redirect_to buses_path
  end

  private
  def user_params
    params.require(:bus).permit(:number, :line_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.create(user_params)
    if @line.valid?
      flash[:notice] = "Line created"
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def show
    @line = Line.find(params[:id])
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    if @line.update(user_params)
      flash[:notice] = "Line has been updated"
      redirect_to line_path(@line)
    else
      render 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    flash[:notice] = "Line has been destroyed"
    redirect_to lines_path
  end

  private
  def user_params
    params.require(:line).permit(:name)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.create(user_params)
    if @station.valid?
       @station.line_ids = params[:station][:line_ids]
      flash[:notice] = "Bus station added"
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def show
    @station =Station.find(params[:id])
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(user_params)
      @station.line_ids = params[:station][:line_ids]
      flash[:notice] = "Bus station updated"
      redirect_to station_path(@station)
    else
      render 'edit'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    flash[:notice] = "Your station has been destroyed"
    redirect_to stations_path
  end

  private
  def user_params
    params.require(:station).permit(:name)
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def index
    @stops = Stop.all
  end

  def new
    @stop = Stop.new
  end

  def create
    @stop = Stop.create(user_params)
    if @stop.valid?
      flash[:notice] = "Stop created"
      redirect_to stops_path
    else
      render 'new'
    end
  end

  def show
    @stop = Stop.find(params[:id])
  end

  def edit
    @stop = Stop.find(params[:id])
  end

  def update
    @stop = Stop.find(params[:id])
    if @stop.update(user_params)
      flash[:notice] = "Stop has been updated"
      redirect_to stop_path(@stop)
    else
      render 'edit'
    end
  end

  def destroy
    @stop = Stop.find(params[:id])
    @stop.delete
    flash[:notice] = "Stop Destroyed"
    redirect_to stops_path
  end

  private
  def user_params
    params.require(:stop).permit(:station_id, :line_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/arrivals/_form.html.erb
<%= render("layouts/errors", :object => @arrival) %>

<%= form_for (@arrival) do |f| %>
  <div class = "form-group">
    <%= f.label "New Arrival Time"%>
    <%= f.text_field :time%>
  </div>
  <div class = "form-group">
    <%= f.collection_select :stop_id, Stop.all, :id, :station_name %>
  </div>
  <div class = "form-group">
    <%= f.collection_select :bus_id, Bus.all, :id, :number %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/arrivals/edit.html.erb
<h1>Edit: <%= @arrival.names %> | <%= @arrival.time %></h1>

<%= render('form') %>

<%= link_to "All Arrivals", arrivals_path, :class => "btn btn-default" %>
<%= link_to "Go Home", root_path, :class => "btn btn-default" %>

app/views/arrivals/index.html.erb
<h1>Arrivals</h1>

<ul>
  <% @arrivals.each do |arrival| %>
    <li><%= link_to "#{arrival.bus.number} / #{arrival.names} / #{arrival.time}", arrival_path(arrival) %></li>
  <% end %>
</ul>

<br><%= link_to "Create New Arrival", new_arrival_path, :class => "btn btn-default" %>
<br>
<br><%= link_to "Home Page", root_path, :class => "btn btn-default" %>

app/views/arrivals/new.html.erb
<h1>Create a New Arrival</h1>

<%= render('form') %>

<p><%= link_to "Arrivals", arrivals_path, :class => 'btn btn-default' %></p>
<p><%= link_to "Home Page", root_path, :class => 'btn btn-default' %></p>

app/views/arrivals/show.html.erb
<h1>Arrival for:</h1>
<h4>| <%= @arrival.bus.number %> | <%= @arrival.names %> | <% @arrival.time %></h4>

<%= link_to "Edit", edit_arrival_path(@arrival), :class => "btn btn-default" %>
<%= link_to "Delete", arrival_path(@arrival),
:data => {:confirm => "Are you sure?", :method => "delete"}, :class => "btn btn-danger" %>
<%= link_to "All Arrivals", arrivals_path, :class => "btn btn-default" %>

app/views/buses/_form.html.erb
<%= render("layouts/errors", :object => @bus) %>

<%= form_for (@bus) do |f| %>
  <p></p>
    <div class = "form-group">
    <%= f.label "Bus Number" %>
    <%= f.text_field :number %>
  </div>
  <p> Choose a line</p>
    <div class = "form-group">
    <%= f.collection_select :line_id, Line.all, :id, :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/buses/edit.html.erb
<h1>Bus Number: <%= @bus.number %></h1>
<p>This bus operates on the: <%= @bus.line.name %></p>

<%= render('form') %>

<p><%= link_to "Home Page", root_path, :class => 'btn btn-default' %></p>

app/views/buses/index.html.erb
<h1>All Buses</h1>

<ul>
<% @buses.each do |bus| %>
  <li><%= link_to bus.number, bus_path(bus) %></li>
<% end %>
</ul>

<p><%= link_to "New Bus", new_bus_path, :class => 'btn btn-default' %></p>
<p><%= link_to "Home Page", root_path, :class => 'btn btn-default' %></p>

app/views/buses/new.html.erb
<h1>Create a New Bus</h1>

<%= render('form') %>

<p><%= link_to "See All Buses", buses_path, :class => 'btn btn-default' %></p>
<p><%= link_to "Home Page", root_path, :class => 'btn btn-default' %></p>

app/views/buses/show.html.erb
<%= content_for(:title, " #{@bus.number} | Bus Station") %>

<h1><%= @bus.number %></h1>
<p>This bus operates on the: <%= @bus.line.name %></p>
<p><%= link_to "Edit", edit_bus_path(@bus), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", bus_path(@bus), :data => {:confirm => "Are you sure?", :method => "delete"},
    :class => "btn btn-danger" %></p>


<%= link_to "See All Buses", buses_path, :class => 'btn btn-default' %>

app/views/home/index.html.erb
<%= content_for(:title, "Bus System") %>

<h1>Welcome to the Bus System!</h1>

<br><br><%= link_to "View / Create Stations", stations_path, :class => 'btn btn-default' %>
<br><br><%= link_to "view / Create Lines", lines_path, :class => 'btn btn-default' %>
<br><br><%= link_to "View / Create Stops", stops_path, :class => 'btn btn-default' %>
<br><br><%= link_to "View / Create Buses", buses_path, :class => 'btn btn-default' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] %>
<%= flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/lines/_form.html.erb
<%= render("layouts/errors", :object => @line) %>

<%= form_for (@line) do |f| %>
  <div class = "form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/lines/edit.html.erb
<%= content_for(:title, "#{@line.name} | Bus Station") %>

<h1>Edit <%= @line.name %></h1>

<%= render 'form' %>

<%= link_to "All Lines", lines_path, :class => "btn btn-default" %>

app/views/lines/index.html.erb
<h1>Lines</h1>

<ul>
<% @lines.each do |line| %>
  <li><%= link_to line.name, line_path(line) %></li>
<% end %>
</ul>

<p><%= link_to "New line", new_line_path, :class => 'btn btn-default' %></p>
<p><%= link_to "Home Page", root_path, :class => 'btn btn-default' %></p>

app/views/lines/new.html.erb
<%= content_for(:title, "New line | Bus Station") %>

<h1>Create a New Line</h1>

<%= render 'form' %>

<%= link_to "All Lines", lines_path, :class => "btn btn-default" %>

app/views/lines/show.html.erb
<%= content_for(:title, " #{@line.name} | Bus Station") %>

<h1><%= @line.name %></h1>

<p><%= link_to "Edit", edit_line_path(@line), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", line_path(@line),
:data => {:confirm => "Are you sure?", :method => "delete"}, :class => "btn btn-danger" %></p>

<%= link_to "All Lines", lines_path, :class => "btn btn-default" %>

app/views/stations/_form.html.erb
<%= render("layouts/errors", :object => @station) %>

<%= form_for (@station) do |f| %>
  <div class = "form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>

  </div>
  <div>
    <% Line.all.each do |line| %>
      <%= check_box_tag "station[line_ids][]", line.id, @station.line_ids.include?(line.id)%>
      <%= line.name %>
  </div>
  <% end %>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/stations/edit.html.erb
<%= content_for(:title, "Edit station | Bus Station") %>

<h1>Edit <%= @station.name %></h1>

<%= render 'form' %>


<%= link_to "Home Page", stations_path, :class => "btn btn-default" %>

app/views/stations/index.html.erb
<h1>Stations</h1>

<ul>
<% @stations.each do |station| %>
  <li><%= link_to station.name, station_path(station) %> </li>
<% end %>
</ul>

<p><%= link_to "New Station", new_station_path, :class => 'btn btn-default' %></p>
<p><%= link_to "Home Page", root_path, :class => 'btn btn-default' %></p>

app/views/stations/new.html.erb
<%= content_for(:title, "New station | Bus Station") %>

<h1>Create a New Station</h1>

<%= render 'form' %>


<%= link_to "All Stations", stations_path, :class => "btn btn-default" %>

app/views/stations/show.html.erb
<%= content_for(:title, " #{@station.name} | Bus Station") %>

<h1><%= @station.name %></h1>

<p><%= link_to "Edit", edit_station_path(@station), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", station_path(@station),
:data => {:confirm => "Are you sure?", :method => "delete"}, :class => "btn btn-danger" %></p>

<%= link_to "Main Station Page", stations_path, :class => "btn btn-default" %>

app/views/stops/_form.html.erb
<%= render("layouts/errors", :object => @stop) %>

<%= form_for (@stop) do |f| %>
  <p>Choose a station</p>
    <div class = "form-group">
    <%= f.collection_select :station_id, Station.all, :id, :name %>
  </div>
  <p> Choose a line</p>
    <div class = "form-group">
    <%= f.collection_select :line_id, Line.all, :id, :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/stops/edit.html.erb
<%= content_for(:title, "#{@stop.station.name} / #{@stop.line.name} | Bus Station") %>

<h1>Edit <%= @stop.station.name + " / " + @stop.line.name %></h1>

<%= render 'form' %>

<%= link_to "All Stops", stops_path, :class => "btn btn-default" %>

app/views/stops/index.html.erb
<h1>Stops</h1>

<ul>
  <% @stops.each do |stop| %>
    <li><%= link_to "#{stop.station.name} / #{stop.line.name}", stop_path(stop) %></li>
  <% end %>
</ul>

<p><%= link_to "New Stop", new_stop_path, :class => 'btn btn-default' %></p>
<p><%= link_to "Home Page", root_path, :class => 'btn btn-default' %></p>

app/views/stops/new.html.erb
<%= content_for(:title, "New Stop | Bus Station") %>

<h1>Create a new stop</h1>

<%= render 'form' %>

<%= link_to "All Stops", stops_path, :class => "btn btn-default" %>

app/views/stops/show.html.erb
<h1><%= @stop.station.name + " / " + @stop.line.name %></h1>

<%= link_to "All Stops", stops_path, :class => "btn btn-default" %>
<p><%= link_to "Edit", edit_stop_path(@stop), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", stop_path(@stop),
:data => {:confirm => "Are you sure?", :method => "delete"}, :class => "btn btn-danger" %></p>

<%= link_to "Main Stops Page", stops_path, :class => "btn btn-default" %>